---

- name: Download NodeJS repository installer
  get_url:
    url: https://deb.nodesource.com/setup_10.x
    dest: /tmp/setup_10.sh
    mode: '0755'

- name: Execute NodeJS repository installer
  shell: /tmp/setup_10.sh
  become: yes

- name: Remove installer
  file:
    path: /tmp/setup_10.sh
    state: absent
    
- name: Update package lists
  apt:
    update_cache: yes
  become: yes
  
- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: 'present'
  vars:
    packages:
      - build-essential
      - git
      - curl
      - nodejs
      - npm
  become: yes
      
- name: Cloning Cloud9 repo
  git:
    repo: "https://github.com/c9/core.git"
    dest: "{{ c9sdk_folder }}"
    depth: 1
  
- name: Running setup
  shell: scripts/install-sdk.sh
  args:
    chdir: "{{ c9sdk_folder }}"
    executable: /bin/bash
